name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
      NODE_VERSION: lts/*  # This will pick the latest LTS version (Node 18)
      IMAGE_NAME: thingsboard
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm packages
        run: |
          npm install -g cross-env 
          npm install -g webpack

      - name: Build the project
        run: |
          mvn license:format install -DskipTests -Ddockerfile.skip=false
          
      - name: list docker images
        run: |
          docker image ls 